baseURL = "http://jockeyclubyrs.dreamspossible.hk/"
languageCode = "zh-tw"
title = "賽馬會青年更新教練計劃"
[[menu.main]]
identifier = "dp"
name = "自在社"
url = "http://www.dreamspossible.hk"
weight = 8
[[menu.main]]
identifier = "contactus"
name = "聯絡我們"
url = "/contact/contact"
weight = 7
[[menu.main]]
identifier = "organization"
name = "感謝機構及導師"
url = "/thanks/thanks"
weight = 6
[[menu.main]]
identifier = "team"
name = "導師及總教練團隊"
url = "/team/team"
weight = 5
[[menu.main]]
identifier = "story"
name = "生命故事"
url = "/story"
weight = 4
[[menu.main]]
identifier = "qa"
name = "常見問題"
url = "/faq/faq"
weight = 3
[[menu.main]]
identifier = "course"
name = "課程介紹"
url = "/course"
weight = 2
[[menu.main]]
identifier = "intro"
name = "緣起"
url = "/intro/intro"
weight = 1
[params]
fblink = "https://www.facebook.com/pg/dp3333/"
youtubelink = "https://www.youtube.com/watch?v=tbfo4mLdc3Y&list=PLbog5WuQqJajS1IkSxEG1JFFneA3nP1Mo"