---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- path: content/contact
  label: Contact
  create: all
- path: content/home
  label: Home
  create: all
- path: content/intro
  label: Intro
  create: all
- path: content/course
  label: Course
  create: all
- path: content/faq
  label: Faq
  create: all
- path: content/story
  label: Story
  create: all
- path: content/team
  label: Team
  create: all
- path: content/thanks
  label: Thanks
  create: all
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.31.1
